farm/apps/product/urls.py
from django.urls import path
from product.views import *

app_name = 'product'

urlpatterns = [
   path('', SignUpCreateView.as_view(), name='signup'),
   path('add/product/',ProductCreateView.as_view(),name='add-product'),
   path('product/list/',ProductListView.as_view(),name='product-list'),
   path('product/update/<int:pk>', ProductUpdateView.as_view(), name='product-update'),
   path('product/delete/<int:pk>', ProductDeleteView.as_view(), name='product-delete'), 
   path('product/detail/<int:pk>', ProductDetailView.as_view(), name='product-detail'),
   path('create_bill/', CustomerDataStore.as_view(), name='create_bill'), 
   path('retrive_bill/<int:pk>/', RetriveBillData.as_view(), name='retrive_bill'), 
   path('bills/', BillList.as_view(), name='bills'), 
  ] 

farm/urls.py
from django.urls import path,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView,LogoutView

urlpatterns = static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace='product')),
	path('login/', LoginView.as_view(template_name='registration/login.html'), name="login"),
    path('logout/', LoginView.as_view(template_name= 'registration/login.html'), name="logout"),
  
]

farm/apps/product/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import ArrayField


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    modified_at = models.DateTimeField(auto_now=True, db_index=True)
    class Meta:
       abstract = True


class User(AbstractUser):
    phone_number = models.CharField(max_length=13)
    address      = models.CharField(max_length=30)
    profile_img  = models.ImageField(upload_to="profile_image/")


class Product(BaseModel):
    name = models.CharField(max_length=20)
    quantity = models.IntegerField()
    product_img = models.ImageField(upload_to="product_image/")
    prize  = models.IntegerField()

    def __str__(self):
        return self.name

class CustomeDetailBill(BaseModel):
    customer_name = models.CharField(max_length=100)
    customer_address = models.CharField(max_length=100)
    customer_number = models.CharField(max_length=13)
    total_list = ArrayField(models.CharField(max_length=255), blank=True)
    product_list = ArrayField(models.CharField(max_length=255), blank=True)
    quantity_list = ArrayField(models.CharField(max_length=255), blank=True)
    unit_price_list = ArrayField(models.CharField(max_length=255), blank=True)
    sub_amount  = models.IntegerField()
    total_amount  = models.IntegerField()

    # product = models.ForeignKey(Product,on_delete=models.CASCADE, related_name='choice_product')
    # is_activate  = models.BooleanField(default = False)

farm/apps/product/forms.py
from django import forms 
from product.models import Product, User, CustomeDetailBill
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
# from bootstrap_datepicker_plus import DatePickerInput


    
class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name','prize','quantity','product_img')


# from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'first_name','last_name', 'email', 'password1', 'password2','address','phone_number','profile_img')
    
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None
    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        name = User.objects.filter(username=username)
        if name.count():
            raise  ValidationError("Username already exists")
        return username

class CustomerBillForm(forms.ModelForm):

    class Meta:
        model = CustomeDetailBill
        fields = ('__all__')

farm/apps/product/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect
from django.views.generic import CreateView,ListView,UpdateView,DeleteView,DetailView
from django.views import View
from .models import Product, User, CustomeDetailBill 
from product.forms import ProductForm, SignUpForm, CustomerBillForm
from .helpers import subscribe_stoke_data
# Create your views here.

class SignUpCreateView(CreateView):
    model = User
    form_class = SignUpForm   
    success_url = '/product/list/'

class ProductCreateView(CreateView):

    model = Product
    form_class = ProductForm   
    success_url = '/product/list/'

    def form_valid(self, form, **kwargs):
        
        product = form.save(commit=False)
        product.save()
        return redirect(self.success_url)


class ProductListView(ListView):
    model = Product
    template_name = 'product/product_list.html'
    
  
class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/product_form.html'
    success_url = '/product/list/'

   
class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'product/product_confirm_delete.html'
    success_url = '/product/list/'

   
class ProductDetailView(DetailView):
    model = Product
    template_name = 'product/product_detail.html'


class CustomerDataStore(View):
    def get(self,request):
        return render(self.request,'billing/product_bill.html')

    def post(self,request):
        try:
            form = CustomerBillForm(request.POST)
            if form.is_valid():
                    subscribe_stoke_data(form)
                    commit_form = form.save(commit=False)
                    commit_form.total_list = request.POST.getlist('total_list')
                    commit_form.product_list = request.POST.getlist('product_list')
                    commit_form.quantity_list = request.POST.getlist('qty_list')
                    commit_form.unit_price_list = request.POST.getlist('unit_price_list')
                    commit_form.save()
                    return redirect('/bills/')
            return render(self.request, 'billing/product_bill.html', {'form': form})
        except Exception as e:
            return render(self.request, 'billing/product_bill.html', {'error':str(e)})
    

class RetriveBillData(View):
    def get(self,request,pk):
        customer_bills = CustomeDetailBill.objects.get(pk=pk)
        return render(self.request, 'billing/retrive_bill_list.html',{'cust_bill':customer_bills})


class BillList(View):
    def get(self,request):
        bills = CustomeDetailBill.objects.all()
        return render(self.request, 'billing/bills_list.html',{'bills':bills})

farm/templates/base.html
{% load static %}  
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Farm</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor2/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor2/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets//vendor2/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor2/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor2/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor2/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor2/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  
</head>

<body>

  <!-- ======= Header ======= -->
   {% include "layout/top-menu.html" %} 
  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">
    <div class="container text-center position-relative" data-aos="fade-in" data-aos-delay="400">
    </div>
  </section><!-- End Hero -->
   {% block content %}{% endblock %}  
  

    <!-- ======= Clients Section ======= -->
    
    <!-- ======= About Section ======= -->
    
    <!-- ======= Counts Section ======= -->
    <!-- End Counts Section -->

    <!-- ======= Why Us Section ======= -->
   <!-- End Why Us Section -->

    <!-- ======= Cta Section ======= -->
    <!-- End Cta Section -->

    <!-- ======= Services Section ======= -->
    <!-- End Services Section -->

    <!-- ======= Portfolio Section ======= -->
   <!-- End Portfolio Section -->

    <!-- ======= Testimonials Section ======= -->
   <!-- End Testimonials Section -->

    <!-- ======= Team Section ======= -->
  <!-- End Team Section -->

    <!-- ======= Contact Section ======= -->
<!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include "layout/footer.html" %}
  <!-- End Footer -->

<!--   <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>
 -->
  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor2/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor2/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor2/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'assets/vendor2/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor2/waypoints/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'assets/vendor2/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'assets/vendor2/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor2/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'assets/vendor2/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'assets/vendor2/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/mmain.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />


  {% block script %}{% endblock %}

</body>

</html>

farm/templates/billing/bills_list.html
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>

<h2>HTML Table</h2>

<table>
  <tr>
    <th>Customer Name</th>
    <th>Customer Address</th>
    <th>Customer Number</th>
    <th>Sub Amount</th>
    <th>Total Amount</th>
  </tr>
  {% for bill in bills %}
  <tr>
    <td><a href="{% url 'product:retrive_bill' bill.id %}">{{bill.customer_name}}</a></td>
    <td>{{bill.customer_address}}</td>
    <td>{{bill.customer_number}}</td>
    <td>{{bill.sub_amount}}</td>
    <td>{{bill.total_amount}}</td>
  </tr>
  {%endfor%}
</table>

</body>
</html>

farm/templates/billing/product_bill.html
{% load static %}
{% load custome %}
<!DOCTYPE html>
<html>
<head>
    <title>Farm</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <!-- toster jsvs script-->
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">
    <!-- End toster jsvs script-->

</head>
<body>

<div id="invoice">
<div class="toolbar hidden-print">
    <div class="text-right">
        <button id="printInvoice" class="btn btn-info"><i class="fa fa-print"></i> Print</button>
    </div>
    <hr>
</div>
<div class="container">
    <div class="card-header">
        Invoice
        <strong>{% today_days %}</strong> 

    </div>
    <div class="card-body">
    <div class="row mb-4">
    <div class="col-sm-6">
    <h6 class="mb-3">From:</h6>
    <div>
    <strong>Webz Poland</strong>
    </div>
    <div>Madalinskiego 8</div>
    <div>71-101 Szczecin, Poland</div>
    <div>Email: info@webz.com.pl</div>
    <div>Phone: +48 444 666 3333</div>
    </div>

    </div>
    <div class="card-header">
        
        <strong>Customer Information</strong> 
          {# <span class="float-right"> <strong>Status:</strong> Pending</span> #}

          {% if error %}
          <script type="text/javascript">toastr.error('{{ error|escape }}', 'Message', {timeOut: 5000});</script>
          {%endif%}
    </div>
<br>
<form method="POST">
    {% csrf_token %}
    {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors %}
              <!--<div class="alert alert-danger">
                <strong>{{ field.label }} : {{ error|escape }}</strong>
              </div>-->
                <!-- Added toster -->
                <script type="text/javascript">toastr.error('{{ error|escape }}', '{{field.label}}', {timeOut: 5000});</script>

            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
              <!--<div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>-->
            <script type="text/javascript">toastr.error('{{ error|escape }}', '{{field.label}}', {timeOut: 5000});</script>
          {% endfor %}
      {% endif %} 
<div class="row">
<div class="col-sm-6">
    <label for="male">Custome Name</label>
    <input type="text" name='customer_name' placeholder='0.00' class="form-control">
</div>
<div class="col-sm-6">
    <label for="male">Customer Address</label>
    <input type="text" name='customer_address' placeholder='0.00' class="form-control">
</div>
<div class="col-sm-6">
    <label for="male">Customer Number</label>
    <input type="text" name='customer_number' placeholder='0.00' class="form-control">
</div>

</div>


<br>

    <div class="table-responsive-sm">
                          <table class="table table-striped" id="tab_logic">
                            <thead>
                              <tr>
                                <th class="text-center"> # </th>
                                <th class="text-center"> Product </th>
                                <th class="text-center"> Qty </th>
                                <th class="text-center"> Price </th>
                                <th class="text-center"> Total </th>
                              </tr>
                            </thead>
                            <tbody>
                              <tr id='addr0'>
                                <td>1</td>
                                {% get_poducts as product_list %}
                                <td>
                                    <select name="product_list" id="cars" class="form-control">
                                    {% for product in product_list %}
                                      <option value="{{product}}">{{product}}</option>
                                    {% endfor %}
                                    </select>
                                </td>
                                <!--<td><input type="text" name='product[]'  placeholder='Enter Product Name' class="form-control"/></td>-->
                                <td ><input type="number" name='qty_list' placeholder='Enter Qty' class="form-control qty" step="0" min="0"/></td>
                                <td><input type="number" name='unit_price_list' placeholder='Enter Unit Price' class="form-control price" step="0.00" min="0"/></td>
                                <td><input type="number" name='total_list' placeholder='0.00' class="form-control total" readonly/></td>
                              </tr>
                              <tr id='addr1'></tr>
                            </tbody>
                          </table>
                        </div>
                      </div>
                      <div class="row clearfix">
                        <div class="col-md-12">
                          <button id="add_row" type="button" class="btn btn-default pull-left">Add Row</button>
                          <button id='delete_row' type="button" class="pull-right btn btn-default">Delete Row</button>
                        </div>
                      </div>
                      <div class="row clearfix" style="margin-top:20px">
                        <div class="col-lg-4 col-sm-5 ml-auto">
                          <table class="table table-clear" id="tab_logic_total">
                            <tbody>
                              <tr>
                                <th class="text-center">Sub Total</th>
                                <td class="text-center"><input type="number" name='sub_amount' placeholder='0.00' class="form-control" id="sub_total" readonly/></td>
                              </tr>
                              <tr>
                                <th class="text-center">CGST</th>
                                <td class="text-center"><div class="input-group mb-2 mb-sm-0">
                                    <input type="number" class="form-control" id="tax" placeholder="0">
                                    <div class="input-group-addon">%</div>
                                  </div></td>
                              </tr>
                              <tr>
                                <th class="text-center">CGST Tax Amount</th>
                                <td class="text-center"><input type="number" name='tax_amount' id="tax_amount" placeholder='0.00' class="form-control" readonly/></td>
                              </tr>
                              <tr>
                                <th class="text-center">Grand Total</th>
                                <td class="text-center"><input type="number" name='total_amount' id="total_amount" placeholder='0.00' class="form-control" readonly/></td>
                              </tr>
                            </tbody>
                          </table>

                        </div>
</div>
    </div>
    </div>
    <button type="submit">Submit</button>
    </form> 

</body>
<script type="text/javascript">
 $('#printInvoice').click(function(){
            Popup($('.invoice'));
            function Popup(data) 
            {
                window.print();
                return true;
            }
        });
$(document).ready(function(){
    var i=1;
    $("#add_row").click(function(){b=i-1;
        $('#addr'+i).html($('#addr'+b).html()).find('td:first-child').html(i+1);
        $('#tab_logic').append('<tr id="addr'+(i+1)+'"></tr>');
        i++; 
    });
    $("#delete_row").click(function(){
        if(i>1){
        $("#addr"+(i-1)).html('');
        i--;
        }
        calc();
    });
    
    $('#tab_logic tbody').on('keyup change',function(){
        calc();
    });
    $('#tax').on('keyup change',function(){
        calc_total();
    });
    

});

function calc()
{
    $('#tab_logic tbody tr').each(function(i, element) {
        var html = $(this).html();
        if(html!='')
        {
            var qty = $(this).find('.qty').val();
            var price = $(this).find('.price').val();
            $(this).find('.total').val(qty*price);
            
            calc_total();
        }
    });
}

function calc_total()
{
    total=0;
    $('.total').each(function() {
        total += parseInt($(this).val());
    });
    $('#sub_total').val(total.toFixed(2));
    tax_sum=total/100*$('#tax').val();
    $('#tax_amount').val(tax_sum.toFixed(2));
    $('#total_amount').val((tax_sum+total).toFixed(2));
}
</script>
</html>

farm/templates/billing/retrive_bill_list.html
<!DOCTYPE html>

<html>
{% load custome %}
<head>
    <title>Farm</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <!-- toster jsvs script-->
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">
    <!-- End toster jsvs script-->

</head>
<body>

<div id="invoice">
<div class="toolbar hidden-print">
    <div class="text-right">
        <button id="printInvoice" class="btn btn-info"><i class="fa fa-print"></i> Print</button>
    </div>
    <hr>
</div>
<div class="container">
    <div class="card-header">
        Invoice
        <strong>Saturday 13/06/2020, 20:58:40</strong> 

    </div>
    <div class="card-body">
    <div class="row mb-4">
    <div class="col-sm-6">
    <h6 class="mb-3">From:</h6>
    <div>
    <strong>Webz Poland</strong>
    </div>
    <div>Madalinskiego 8</div>
    <div>71-101 Szczecin, Poland</div>
    <div>Email: info@webz.com.pl</div>
    <div>Phone: +48 444 666 3333</div>
    </div>

    </div>
    <div class="card-header">
        
        <strong>Customer Information</strong> 
          

          
    </div>
<br>
<form method="POST">
    <input type="hidden" name="csrfmiddlewaretoken" value="0mwhypZpGFqmaBzOfrWUNDGcWr1KoQvU3TrW7AJEiNMLX4mqWo0uaMSi4ll5g47r">
     
<div class="row">
<div class="col-sm-6">
    <label for="male">Custome Name</label> : {{cust_bill.customer_name}}
</div>
<div class="col-sm-6">
    <label for="male">Customer Address</label> : {{cust_bill.customer_address}}
</div>
<div class="col-sm-6">
    <label for="male">Customer Number</label>: {{cust_bill.customer_number}}
</div>

</div>


<br>

    <div class="table-responsive-sm">
                          <table class="table table-striped" id="tab_logic">
                            <thead>
                              <tr>
                                <th class="text-center"> # </th>
                                <th class="text-center"> Product </th>
                                <th class="text-center"> Qty </th>
                                <th class="text-center"> Price </th>
                                <th class="text-center"> Total </th>
                              </tr>
                            </thead>
                            <tbody>

   						{% filter_bill cust_bill as bills %}	
   							{% for bill in bills %}
                              <tr id='addr0'>
                                <td class="text-center">{{ forloop.counter }}</td>

                                <td class="text-center">{{bill.product_list}}</td>
                                
                                <!--<td><input type="text" name='product[]'  placeholder='Enter Product Name' class="form-control"/></td>-->
                                <td class="text-center">{{bill.quantity_list}}</td>
                                <td class="text-center">{{bill.unit_price_list}}</td>
                                <td class="text-center">{{bill.total_list}}</td>
                              </tr>
                              <tr id='addr1'></tr>
                              {% endfor %}
                            </tbody>
                          </table>
                        </div>
                      </div>
                      
                      <div class="row clearfix" style="margin-top:20px">
                        <div class="col-lg-4 col-sm-5 ml-auto">
                          <table class="table table-clear" id="tab_logic_total">
                            <tbody>
                              <tr>
                                <th class="text-center">Sub Total</th>
                                <td class="text-center">{{cust_bill.sub_amount}}</td>
                              </tr>
                              <tr>
                                <th class="text-center">CGST</th>
                                <td class="text-center">0%</td>
                              </tr>
                              <tr>
                                <th class="text-center">CGST Tax Amount</th>
                                <td class="text-center">0</td>
                              </tr>
                              <tr>
                                <th class="text-center">Grand Total</th>
                                <td class="text-center">{{cust_bill.total_amount}}</td>
                              </tr>
                            </tbody>
                          </table>

                        </div>
</div>
    </div>
    </div>
    <button type="submit">Submit</button>
    </form> 

</body>
<script type="text/javascript">
 $('#printInvoice').click(function(){
            Popup($('.invoice'));
            function Popup(data) 
            {
                window.print();
                return true;
            }
        });
</script>
</html>

farm/templates/layout/footer.html
{% load static %}  
<footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Farm</h3>
            <p>
              AB road <br>
              Magharkhedi,452001<br>
              India <br><br>
              <strong>Phone:</strong> +91 79991-62975<br>
              <strong>Email:</strong> farm@gmail.com<br>
            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="/">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="/about/property">About us</a></li>
             
            </ul>
          </div>

          
          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Join Our Farm</h4>
            <p>Multiple Questions of yours with single answer Our Farm !!</p>
            
          </div>

        </div>
      </div>
    </div>

    <!-- <div class="container d-md-flex py-4">

      <div class="mr-md-auto text-center text-md-left">
        <div class="copyright">
          &copy; Copyright <strong><span>Bethany</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>-->
  </footer>

farm/templates/product/product_detail.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
  <div class="container">        
            <h2>Details</h2>
          <table class="table table-striped">
            <thead>
              <tr>
                <th></th>
                <th>Name</th>
                <th>Quantity</th>
                <th>Prize</th>
              </tr>
            </thead>
            <tbody>
            <tr>
                   <td> {% if object.product_img  %}
                   <a href="{% url 'product:product-detail' object.id %}">
                   <img src="{{ object.product_img.url }}" width="400" height="200">
                   </a>
                   {% endif %}</td>
                   
                   <td>{{ object.name }}</td>
                   <td>{{ object.quantity }}</td>
                   <td> {{ object.prize }}</td>

                  </tr>

            </tbody>
          </table>
        </div>

{% endblock %}



 

farm/templates/product/product_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}

            <h2>Product List</h2>
          <table class="table table-striped">
            <thead>
              <tr>
                <th></th>
                <th>Name</th>
                <th>Quantity</th>
                <th>Prize</th>
               
              </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                  <tr>
                   <td> {% if object.product_img  %}
                   <a href="{% url 'product:product-detail' object.id %}">
                   <img src="{{ object.product_img.url }}" width="400" height="200">
                   </a>
                   {% endif %}</td>

                   <td>{{ object.name }}</td>
                   <td>{{ object.quantity }}</td>
                   <td> {{ object.prize }}</td>
                   <td><a href="{% url 'product:product-update' object.id %}">Update</a>/<a href="{% url 'product:product-delete' object.id %}">Delete</a></td> 
                   
                  </tr>
                {% endfor %}
            </tbody>
          </table>



{% endblock %}